//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Quotations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoLeasingQuotationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoLeasingQuotationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Quotations.AutoLeasingQuotationResources", typeof(AutoLeasingQuotationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation Settings Not Found.
        /// </summary>
        public static string DepreciationSettingsNotFound {
            get {
                return ResourceManager.GetString("DepreciationSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not allowed Companies for the bank.
        /// </summary>
        public static string InsuranceCompaniesNotAssignedToTheBank {
            get {
                return ResourceManager.GetString("InsuranceCompaniesNotAssignedToTheBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company not allowed for the bank.
        /// </summary>
        public static string NotAllowedInsuranceCompany {
            get {
                return ResourceManager.GetString("NotAllowedInsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Method History Settings not found for this external ID.
        /// </summary>
        public static string RepairMethodHistorySettingsNotFoundForThisExternalId {
            get {
                return ResourceManager.GetString("RepairMethodHistorySettingsNotFoundForThisExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Method Settings Not Found For This Bank.
        /// </summary>
        public static string RepairMethodSettingsNotFoundForThisBank {
            get {
                return ResourceManager.GetString("RepairMethodSettingsNotFoundForThisBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
    }
}
