//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Corporate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorporateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorporateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Corporate.CorporateResources", typeof(CorporateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Already Locked.
        /// </summary>
        public static string AccountAlreadyLocked {
            get {
                return ResourceManager.GetString("AccountAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Already Unlocked.
        /// </summary>
        public static string AccountAlreadyUnLocked {
            get {
                return ResourceManager.GetString("AccountAlreadyUnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked Successfully.
        /// </summary>
        public static string AccountLockedSuccessfully {
            get {
                return ResourceManager.GetString("AccountLockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Unlocked Successfully.
        /// </summary>
        public static string AccountUnLockedSuccessfully {
            get {
                return ResourceManager.GetString("AccountUnLockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Corporate User.
        /// </summary>
        public static string AddCorporateUser {
            get {
                return ResourceManager.GetString("AddCorporateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate User Added Successfully.
        /// </summary>
        public static string CorporateUserAddedSuccessfully {
            get {
                return ResourceManager.GetString("CorporateUserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style = &apos;font-size:16;font-familty:Helvetica !important;&apos; dir=LTR&gt;&lt;hr&gt;&lt;br/&gt;&lt;h2&gt; Dear user ,&lt;/h2&gt;&lt;br/&gt; Your wallet balance is running low, please recharge.&lt;br/&gt; Your current balance: {0} SAR   &lt;/div&gt;.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Balance Recharge.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Email.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Name.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Password.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Phone Number.
        /// </summary>
        public static string EmptyPhoneNumber {
            get {
                return ResourceManager.GetString("EmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty RePassword.
        /// </summary>
        public static string EmptyRePassword {
            get {
                return ResourceManager.GetString("EmptyRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (G-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string login_incorrect_password_message {
            get {
                return ResourceManager.GetString("login_incorrect_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalOTP:.
        /// </summary>
        public static string OtpSmsBody_Portal {
            get {
                return ResourceManager.GetString("OtpSmsBody_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Matched.
        /// </summary>
        public static string PasswordNotMatched {
            get {
                return ResourceManager.GetString("PasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Password.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
