//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tameenk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Policy.PolicyResource", typeof(PolicyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tameenk | Insurance Policy.
        /// </summary>
        internal static string FailedPolicyEmailSubject {
            get {
                return ResourceManager.GetString("FailedPolicyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicyFailedEmailBody {
            get {
                return ResourceManager.GetString("PolicyFailedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessComp_ACIGEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessComp_ACIGEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessComp_TokioMarineEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessComp_TokioMarineEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessComp_TUICEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessComp_TUICEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessComp_UCAEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessComp_UCAEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessCompEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessCompEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessMotorPlusEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessMotorPlusEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessSanadPlusEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessSanadPlusEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessTPLEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessTPLEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicySuccessWafiCompEmailBody {
            get {
                return ResourceManager.GetString("PolicySuccessWafiCompEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tameenk | Insurance Policy No {0}.
        /// </summary>
        internal static string SuccessPolicyEmailSubject {
            get {
                return ResourceManager.GetString("SuccessPolicyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt; Dear customer,&lt;/h1&gt;&lt;hr&gt;&lt;br /&gt;&lt;h2&gt; Attached is your purchased policy for your records along with payment invoice.&lt;/h2&gt;&lt;h2&gt; For Policy file Please &lt;a href = &apos;PolicyFileUrl&apos; &gt; Click here &lt;/a&gt;&lt;/ h2 &gt;&lt;h2&gt; Thanks for giving us the chance of serving you.&lt;/h2 &gt; .
        /// </summary>
        internal static string TawuniyaSuccessPolicyEmailBody {
            get {
                return ResourceManager.GetString("TawuniyaSuccessPolicyEmailBody", resourceCulture);
            }
        }
    }
}
