//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Services.InquiryGateway.NajmBcareService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NajmBcareService.INCDService")]
    public interface INCDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INCDService/NCDEligibility", ReplyAction="http://tempuri.org/INCDService/NCDEligibilityResponse")]
        string NCDEligibility(long personId, int vehicleIdentifier, System.Nullable<long> vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INCDService/NCDEligibility", ReplyAction="http://tempuri.org/INCDService/NCDEligibilityResponse")]
        System.Threading.Tasks.Task<string> NCDEligibilityAsync(long personId, int vehicleIdentifier, System.Nullable<long> vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INCDServiceChannel : Tameenk.Services.InquiryGateway.NajmBcareService.INCDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NCDServiceClient : System.ServiceModel.ClientBase<Tameenk.Services.InquiryGateway.NajmBcareService.INCDService>, Tameenk.Services.InquiryGateway.NajmBcareService.INCDService {
        
        public NCDServiceClient() {
        }
        
        public NCDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NCDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NCDEligibility(long personId, int vehicleIdentifier, System.Nullable<long> vehicleId) {
            return base.Channel.NCDEligibility(personId, vehicleIdentifier, vehicleId);
        }
        
        public System.Threading.Tasks.Task<string> NCDEligibilityAsync(long personId, int vehicleIdentifier, System.Nullable<long> vehicleId) {
            return base.Channel.NCDEligibilityAsync(personId, vehicleIdentifier, vehicleId);
        }
    }
}
