//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Profile.ProfileResources", typeof(ProfileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddCorporateUser {
            get {
                return ResourceManager.GetString("AddCorporateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string changePasswordSuccess {
            get {
                return ResourceManager.GetString("changePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password is empty.
        /// </summary>
        public static string confirmNewPasswordEmpty {
            get {
                return ResourceManager.GetString("confirmNewPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is empty.
        /// </summary>
        public static string EmptyUserId {
            get {
                return ResourceManager.GetString("EmptyUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (V-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened during sending OTP.
        /// </summary>
        public static string ErrorOTPSend {
            get {
                return ResourceManager.GetString("ErrorOTPSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured National ID.
        /// </summary>
        public static string InsuredNIN {
            get {
                return ResourceManager.GetString("InsuredNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string login_password_error {
            get {
                return ResourceManager.GetString("login_password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be less than 4 digits.
        /// </summary>
        public static string login_password_error1 {
            get {
                return ResourceManager.GetString("login_password_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id is empty.
        /// </summary>
        public static string nationalIdEmpty {
            get {
                return ResourceManager.GetString("nationalIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password doesn&apos;t match..
        /// </summary>
        public static string newpassword_confirm_error {
            get {
                return ResourceManager.GetString("newpassword_confirm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is empty.
        /// </summary>
        public static string newPasswordEmpty {
            get {
                return ResourceManager.GetString("newPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Addresses Found.
        /// </summary>
        public static string NoAddressFound {
            get {
                return ResourceManager.GetString("NoAddressFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is empty.
        /// </summary>
        public static string oldPasswordEmpty {
            get {
                return ResourceManager.GetString("oldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code was sent to your phone .Please check it..
        /// </summary>
        public static string OTPSent {
            get {
                return ResourceManager.GetString("OTPSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password doesn&apos;t match..
        /// </summary>
        public static string password_confirm_error {
            get {
                return ResourceManager.GetString("password_confirm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This national id {0} has reached the maximum number of updates.
        /// </summary>
        public static string ReachedToMaximum {
            get {
                return ResourceManager.GetString("ReachedToMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter another phone, as the entered phone is the same current user account.
        /// </summary>
        public static string SameAccountPhone {
            get {
                return ResourceManager.GetString("SameAccountPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence/Custom Card Number.
        /// </summary>
        public static string SequenceOrCustomCardNumber {
            get {
                return ResourceManager.GetString("SequenceOrCustomCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is currently down, please try again later.
        /// </summary>
        public static string ServiceDown {
            get {
                return ResourceManager.GetString("ServiceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string UnLocked {
            get {
                return ResourceManager.GetString("UnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reached tha max limit to update your data in current year.
        /// </summary>
        public static string UpdatePhoneMaxLimit {
            get {
                return ResourceManager.GetString("UpdatePhoneMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not update your data more than 1 time in less than 24 hours.
        /// </summary>
        public static string UpdatePhoneMaxLimitPerDay {
            get {
                return ResourceManager.GetString("UpdatePhoneMaxLimitPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email was sent to this email: {0} ..
        /// </summary>
        public static string VerificationMailAlreadySent {
            get {
                return ResourceManager.GetString("VerificationMailAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCare account verification code to update account info is {0}.
        /// </summary>
        public static string VerifyOTP {
            get {
                return ResourceManager.GetString("VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Payment.
        /// </summary>
        public static string WaitForPayment {
            get {
                return ResourceManager.GetString("WaitForPayment", resourceCulture);
            }
        }
    }
}
