//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Common.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Common.Utilities.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicLoginPageUrl.
        /// </summary>
        public static string ArabicLoginPageUrl {
            get {
                return ResourceManager.GetString("ArabicLoginPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicLoginWithCaptchaPageUrl.
        /// </summary>
        public static string ArabicLoginWithCaptchaPageUrl {
            get {
                return ResourceManager.GetString("ArabicLoginWithCaptchaPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicRegisterPageUrl.
        /// </summary>
        public static string ArabicRegisterPageUrl {
            get {
                return ResourceManager.GetString("ArabicRegisterPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicVideosListUrl.
        /// </summary>
        public static string ArabicVideosListUrl {
            get {
                return ResourceManager.GetString("ArabicVideosListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseSiteUrl.
        /// </summary>
        public static string BaseSiteUrl {
            get {
                return ResourceManager.GetString("BaseSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%Body%].
        /// </summary>
        public static string bodyMailReplace {
            get {
                return ResourceManager.GetString("bodyMailReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptchaLimit.
        /// </summary>
        public static string CaptchaLimit {
            get {
                return ResourceManager.GetString("CaptchaLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECareResource.
        /// </summary>
        public static string ECareResource {
            get {
                return ResourceManager.GetString("ECareResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishLoginPageUrl.
        /// </summary>
        public static string EnglishLoginPageUrl {
            get {
                return ResourceManager.GetString("EnglishLoginPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishLoginWithCaptchaPageUrl.
        /// </summary>
        public static string EnglishLoginWithCaptchaPageUrl {
            get {
                return ResourceManager.GetString("EnglishLoginWithCaptchaPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishRegisterPageUrl.
        /// </summary>
        public static string EnglishRegisterPageUrl {
            get {
                return ResourceManager.GetString("EnglishRegisterPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishVideosListUrl.
        /// </summary>
        public static string EnglishVideosListUrl {
            get {
                return ResourceManager.GetString("EnglishVideosListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X04}.
        /// </summary>
        public static string FormateBody {
            get {
                return ResourceManager.GetString("FormateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfotainmentSMSPassword.
        /// </summary>
        public static string InfotainmentSMSPassword {
            get {
                return ResourceManager.GetString("InfotainmentSMSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfotainmentSMSUserName.
        /// </summary>
        public static string InfotainmentSMSUserName {
            get {
                return ResourceManager.GetString("InfotainmentSMSUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalidCaptchaLogins.
        /// </summary>
        public static string invalidCaptchaLogins {
            get {
                return ResourceManager.GetString("invalidCaptchaLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalidLogins.
        /// </summary>
        public static string invalidLogins {
            get {
                return ResourceManager.GetString("invalidLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        ///        a {
        ///            text-decoration: none !important;
        ///        }
        ///
        ///        .ExternalClass {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailContainer {
            get {
                return ResourceManager.GetString("MailContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainMailContainer.
        /// </summary>
        public static string MainMailContainer {
            get {
                return ResourceManager.GetString("MainMailContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberShipProviderName.
        /// </summary>
        public static string MemberShipProviderName {
            get {
                return ResourceManager.GetString("MemberShipProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSS_SQL_Group.
        /// </summary>
        public static string MOSS_SQL_Group {
            get {
                return ResourceManager.GetString("MOSS_SQL_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrangeDSLPublicSiteUrl.
        /// </summary>
        public static string OrangeDSLPublicSiteUrl {
            get {
                return ResourceManager.GetString("OrangeDSLPublicSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicSiteURL.
        /// </summary>
        public static string PublicSiteURL {
            get {
                return ResourceManager.GetString("PublicSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6Le1mAUTAAAAAH-2qCy0_YATsyvptCRUVP4-0iAx.
        /// </summary>
        public static string RecaptchaSecretKey {
            get {
                return ResourceManager.GetString("RecaptchaSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/recaptcha/api/siteverify?secret={0}&amp;response={1}.
        /// </summary>
        public static string RecaptchaWebApi {
            get {
                return ResourceManager.GetString("RecaptchaWebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;(.|\n)+?&gt;.
        /// </summary>
        public static string RegEx1 {
            get {
                return ResourceManager.GetString("RegEx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;(.|\n)+?&gt;.
        /// </summary>
        public static string RegEx11 {
            get {
                return ResourceManager.GetString("RegEx11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SANDSite.
        /// </summary>
        public static string SANDSite {
            get {
                return ResourceManager.GetString("SANDSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfProvisioningRegistrationMsg.
        /// </summary>
        public static string SelfProvisioningRegistrationMsg {
            get {
                return ResourceManager.GetString("SelfProvisioningRegistrationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowSiteActionMenu.
        /// </summary>
        public static string ShowSiteActionMenu {
            get {
                return ResourceManager.GetString("ShowSiteActionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%SiteUrl%].
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSpassword.
        /// </summary>
        public static string SMSpassword {
            get {
                return ResourceManager.GetString("SMSpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSTitle.
        /// </summary>
        public static string SMSTitle {
            get {
                return ResourceManager.GetString("SMSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSUsername.
        /// </summary>
        public static string SMSUsername {
            get {
                return ResourceManager.GetString("SMSUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTPServer.
        /// </summary>
        public static string SMTPServer {
            get {
                return ResourceManager.GetString("SMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
