//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Services.Inquiry.Components.NajmInsuranceInquiryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NajmInsuranceInquiryService.IInsuranceInquiry")]
    public interface IInsuranceInquiry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetail", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailResponse")]
        string GetDriverCaseDetail(string driverId, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetail", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailResponse")]
        System.Threading.Tasks.Task<string> GetDriverCaseDetailAsync(string driverId, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailWithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailWithInquiryTypeResponse")]
        string GetDriverCaseDetailWithInquiryType(string driverId, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailWithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailWithInquiryTypeResponse")]
        System.Threading.Tasks.Task<string> GetDriverCaseDetailWithInquiryTypeAsync(string driverId, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2Response")]
        string GetDriverCaseDetailV2(string driverId, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2Response")]
        System.Threading.Tasks.Task<string> GetDriverCaseDetailV2Async(string driverId, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2WithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2WithInquiryTypeResponse" +
            "")]
        string GetDriverCaseDetailV2WithInquiryType(string driverId, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2WithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetDriverCaseDetailV2WithInquiryTypeResponse" +
            "")]
        System.Threading.Tasks.Task<string> GetDriverCaseDetailV2WithInquiryTypeAsync(string driverId, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetail", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailResponse")]
        string GetVehicleCaseDetail(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetail", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailResponse")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailWithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailWithInquiryTypeResponse")]
        string GetVehicleCaseDetailWithInquiryType(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailWithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailWithInquiryTypeResponse")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailWithInquiryTypeAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2Response")]
        string GetVehicleCaseDetailV2(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2Response")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailV2Async(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2WithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2WithInquiryTypeRespons" +
            "e")]
        string GetVehicleCaseDetailV2WithInquiryType(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2WithInquiryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailV2WithInquiryTypeRespons" +
            "e")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailV2WithInquiryTypeAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoResponse")]
        string GetVehicleMultiInsuranceByPlateNo(string vehiclePlateNo, int registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoResponse")]
        System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceByPlateNoAsync(string vehiclePlateNo, int registrationType, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoWithInquiry" +
            "Type", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoWithInquiry" +
            "TypeResponse")]
        string GetVehicleMultiInsuranceByPlateNoWithInquiryType(string vehiclePlateNo, int registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoWithInquiry" +
            "Type", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceByPlateNoWithInquiry" +
            "TypeResponse")]
        System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceByPlateNoWithInquiryTypeAsync(string vehiclePlateNo, int registrationType, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoResponse" +
            "")]
        string GetVehicleMultiInsuranceBySequenceNo(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoResponse" +
            "")]
        System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceBySequenceNoAsync(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoWithInqu" +
            "iryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoWithInqu" +
            "iryTypeResponse")]
        string GetVehicleMultiInsuranceBySequenceNoWithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoWithInqu" +
            "iryType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleMultiInsuranceBySequenceNoWithInqu" +
            "iryTypeResponse")]
        System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceBySequenceNoWithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoResponse")]
        string GetVehicleCaseDetailBySequenceNo(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNo", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoResponse")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoAsync(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoWithInquiryT" +
            "ype", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoWithInquiryT" +
            "ypeResponse")]
        string GetVehicleCaseDetailBySequenceNoWithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoWithInquiryT" +
            "ype", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoWithInquiryT" +
            "ypeResponse")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoWithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2Response")]
        string GetVehicleCaseDetailBySequenceNoV2(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2Response")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoV2Async(string vehicleSequenceno, int insuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2WithInquir" +
            "yType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2WithInquir" +
            "yTypeResponse")]
        string GetVehicleCaseDetailBySequenceNoV2WithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2WithInquir" +
            "yType", ReplyAction="http://tempuri.org/IInsuranceInquiry/GetVehicleCaseDetailBySequenceNoV2WithInquir" +
            "yTypeResponse")]
        System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoV2WithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsuranceInquiryChannel : Tameenk.Services.Inquiry.Components.NajmInsuranceInquiryService.IInsuranceInquiry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsuranceInquiryClient : System.ServiceModel.ClientBase<Tameenk.Services.Inquiry.Components.NajmInsuranceInquiryService.IInsuranceInquiry>, Tameenk.Services.Inquiry.Components.NajmInsuranceInquiryService.IInsuranceInquiry {
        
        public InsuranceInquiryClient() {
        }
        
        public InsuranceInquiryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsuranceInquiryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsuranceInquiryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsuranceInquiryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDriverCaseDetail(string driverId, int insuranceID) {
            return base.Channel.GetDriverCaseDetail(driverId, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetDriverCaseDetailAsync(string driverId, int insuranceID) {
            return base.Channel.GetDriverCaseDetailAsync(driverId, insuranceID);
        }
        
        public string GetDriverCaseDetailWithInquiryType(string driverId, int insuranceID, int inquiryType) {
            return base.Channel.GetDriverCaseDetailWithInquiryType(driverId, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetDriverCaseDetailWithInquiryTypeAsync(string driverId, int insuranceID, int inquiryType) {
            return base.Channel.GetDriverCaseDetailWithInquiryTypeAsync(driverId, insuranceID, inquiryType);
        }
        
        public string GetDriverCaseDetailV2(string driverId, int insuranceID) {
            return base.Channel.GetDriverCaseDetailV2(driverId, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetDriverCaseDetailV2Async(string driverId, int insuranceID) {
            return base.Channel.GetDriverCaseDetailV2Async(driverId, insuranceID);
        }
        
        public string GetDriverCaseDetailV2WithInquiryType(string driverId, int insuranceID, int inquiryType) {
            return base.Channel.GetDriverCaseDetailV2WithInquiryType(driverId, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetDriverCaseDetailV2WithInquiryTypeAsync(string driverId, int insuranceID, int inquiryType) {
            return base.Channel.GetDriverCaseDetailV2WithInquiryTypeAsync(driverId, insuranceID, inquiryType);
        }
        
        public string GetVehicleCaseDetail(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID) {
            return base.Channel.GetVehicleCaseDetail(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailAsync(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public string GetVehicleCaseDetailWithInquiryType(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailWithInquiryType(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailWithInquiryTypeAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailWithInquiryTypeAsync(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public string GetVehicleCaseDetailV2(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailV2(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailV2Async(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailV2Async(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public string GetVehicleCaseDetailV2WithInquiryType(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailV2WithInquiryType(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailV2WithInquiryTypeAsync(string vehiclePlateNo, System.Nullable<int> registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailV2WithInquiryTypeAsync(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public string GetVehicleMultiInsuranceByPlateNo(string vehiclePlateNo, int registrationType, int insuranceID) {
            return base.Channel.GetVehicleMultiInsuranceByPlateNo(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceByPlateNoAsync(string vehiclePlateNo, int registrationType, int insuranceID) {
            return base.Channel.GetVehicleMultiInsuranceByPlateNoAsync(vehiclePlateNo, registrationType, insuranceID);
        }
        
        public string GetVehicleMultiInsuranceByPlateNoWithInquiryType(string vehiclePlateNo, int registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleMultiInsuranceByPlateNoWithInquiryType(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceByPlateNoWithInquiryTypeAsync(string vehiclePlateNo, int registrationType, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleMultiInsuranceByPlateNoWithInquiryTypeAsync(vehiclePlateNo, registrationType, insuranceID, inquiryType);
        }
        
        public string GetVehicleMultiInsuranceBySequenceNo(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleMultiInsuranceBySequenceNo(vehicleSequenceno, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceBySequenceNoAsync(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleMultiInsuranceBySequenceNoAsync(vehicleSequenceno, insuranceID);
        }
        
        public string GetVehicleMultiInsuranceBySequenceNoWithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleMultiInsuranceBySequenceNoWithInquiryType(vehicleSequenceno, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleMultiInsuranceBySequenceNoWithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleMultiInsuranceBySequenceNoWithInquiryTypeAsync(vehicleSequenceno, insuranceID, inquiryType);
        }
        
        public string GetVehicleCaseDetailBySequenceNo(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailBySequenceNo(vehicleSequenceno, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoAsync(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoAsync(vehicleSequenceno, insuranceID);
        }
        
        public string GetVehicleCaseDetailBySequenceNoWithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoWithInquiryType(vehicleSequenceno, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoWithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoWithInquiryTypeAsync(vehicleSequenceno, insuranceID, inquiryType);
        }
        
        public string GetVehicleCaseDetailBySequenceNoV2(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoV2(vehicleSequenceno, insuranceID);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoV2Async(string vehicleSequenceno, int insuranceID) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoV2Async(vehicleSequenceno, insuranceID);
        }
        
        public string GetVehicleCaseDetailBySequenceNoV2WithInquiryType(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoV2WithInquiryType(vehicleSequenceno, insuranceID, inquiryType);
        }
        
        public System.Threading.Tasks.Task<string> GetVehicleCaseDetailBySequenceNoV2WithInquiryTypeAsync(string vehicleSequenceno, int insuranceID, int inquiryType) {
            return base.Channel.GetVehicleCaseDetailBySequenceNoV2WithInquiryTypeAsync(vehicleSequenceno, insuranceID, inquiryType);
        }
    }
}
