//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Vehicles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LicenseTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Vehicles.LicenseTypeResource", typeof(LicenseTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAVY TRANSPORT.
        /// </summary>
        public static string HEAVYTRANSPORT {
            get {
                return ResourceManager.GetString("HEAVYTRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARGE BUS.
        /// </summary>
        public static string LARGEBUS {
            get {
                return ResourceManager.GetString("LARGEBUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT TRANSPORT.
        /// </summary>
        public static string LIGHTTRANSPORT {
            get {
                return ResourceManager.GetString("LIGHTTRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTORCYCLE.
        /// </summary>
        public static string MOTORCYCLE {
            get {
                return ResourceManager.GetString("MOTORCYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICKUP / PASSING CARS.
        /// </summary>
        public static string PICKUPPASSINGCARS {
            get {
                return ResourceManager.GetString("PICKUPPASSINGCARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE.
        /// </summary>
        public static string PRIVATE {
            get {
                return ResourceManager.GetString("PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC PRIVATE.
        /// </summary>
        public static string PUBLICPRIVATE {
            get {
                return ResourceManager.GetString("PUBLICPRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC TAXI.
        /// </summary>
        public static string PUBLICTAXI {
            get {
                return ResourceManager.GetString("PUBLICTAXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC WORKS VEHICLES.
        /// </summary>
        public static string PUBLICWORKSVEHICLES {
            get {
                return ResourceManager.GetString("PUBLICWORKSVEHICLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALL BUS.
        /// </summary>
        public static string SMALLBUS {
            get {
                return ResourceManager.GetString("SMALLBUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPORARY LICENSE (PERMISSION).
        /// </summary>
        public static string TEMPORARY {
            get {
                return ResourceManager.GetString("TEMPORARY", resourceCulture);
            }
        }
    }
}
