//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Payment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HyperPayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HyperPayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Payment.HyperPayResource", typeof(HyperPayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined for unknown reason.
        /// </summary>
        public static string Error_700500003 {
            get {
                return ResourceManager.GetString("Error_700500003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined for unknown reason.
        /// </summary>
        public static string Error_800100100 {
            get {
                return ResourceManager.GetString("Error_800100100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (refund on gambling tx not allowed).
        /// </summary>
        public static string Error_800100150 {
            get {
                return ResourceManager.GetString("Error_800100150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid card).
        /// </summary>
        public static string Error_800100151 {
            get {
                return ResourceManager.GetString("Error_800100151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined by authorization system.
        /// </summary>
        public static string Error_800100152 {
            get {
                return ResourceManager.GetString("Error_800100152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid CVV).
        /// </summary>
        public static string Error_800100153 {
            get {
                return ResourceManager.GetString("Error_800100153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (transaction marked as invalid).
        /// </summary>
        public static string Error_800100154 {
            get {
                return ResourceManager.GetString("Error_800100154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (amount exceeds credit).
        /// </summary>
        public static string Error_800100155 {
            get {
                return ResourceManager.GetString("Error_800100155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (format error).
        /// </summary>
        public static string Error_800100156 {
            get {
                return ResourceManager.GetString("Error_800100156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (wrong expiry date).
        /// </summary>
        public static string Error_800100157 {
            get {
                return ResourceManager.GetString("Error_800100157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (suspecting manipulation).
        /// </summary>
        public static string Error_800100158 {
            get {
                return ResourceManager.GetString("Error_800100158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (stolen card).
        /// </summary>
        public static string Error_800100159 {
            get {
                return ResourceManager.GetString("Error_800100159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (card blocked).
        /// </summary>
        public static string Error_800100160 {
            get {
                return ResourceManager.GetString("Error_800100160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (too many invalid tries).
        /// </summary>
        public static string Error_800100161 {
            get {
                return ResourceManager.GetString("Error_800100161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (limit exceeded).
        /// </summary>
        public static string Error_800100162 {
            get {
                return ResourceManager.GetString("Error_800100162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (maximum transaction frequency exceeded).
        /// </summary>
        public static string Error_800100163 {
            get {
                return ResourceManager.GetString("Error_800100163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (merchants limit exceeded).
        /// </summary>
        public static string Error_800100164 {
            get {
                return ResourceManager.GetString("Error_800100164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (card lost).
        /// </summary>
        public static string Error_800100165 {
            get {
                return ResourceManager.GetString("Error_800100165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (Incorrect personal identification number).
        /// </summary>
        public static string Error_800100166 {
            get {
                return ResourceManager.GetString("Error_800100166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (referencing transaction does not match).
        /// </summary>
        public static string Error_800100167 {
            get {
                return ResourceManager.GetString("Error_800100167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (restricted card).
        /// </summary>
        public static string Error_800100168 {
            get {
                return ResourceManager.GetString("Error_800100168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (card type is not processed by the authorization center).
        /// </summary>
        public static string Error_800100169 {
            get {
                return ResourceManager.GetString("Error_800100169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (transaction not permitted).
        /// </summary>
        public static string Error_800100170 {
            get {
                return ResourceManager.GetString("Error_800100170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (pick up card).
        /// </summary>
        public static string Error_800100171 {
            get {
                return ResourceManager.GetString("Error_800100171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (account blocked).
        /// </summary>
        public static string Error_800100172 {
            get {
                return ResourceManager.GetString("Error_800100172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid currency, not processed by authorization center).
        /// </summary>
        public static string Error_800100173 {
            get {
                return ResourceManager.GetString("Error_800100173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid amount).
        /// </summary>
        public static string Error_800100174 {
            get {
                return ResourceManager.GetString("Error_800100174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid brand).
        /// </summary>
        public static string Error_800100175 {
            get {
                return ResourceManager.GetString("Error_800100175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (account temporarily not available. Please try again later).
        /// </summary>
        public static string Error_800100176 {
            get {
                return ResourceManager.GetString("Error_800100176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (amount field should not be empty).
        /// </summary>
        public static string Error_800100177 {
            get {
                return ResourceManager.GetString("Error_800100177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (PIN entered incorrectly too often).
        /// </summary>
        public static string Error_800100178 {
            get {
                return ResourceManager.GetString("Error_800100178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (exceeds withdrawal count limit).
        /// </summary>
        public static string Error_800100179 {
            get {
                return ResourceManager.GetString("Error_800100179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid configuration data).
        /// </summary>
        public static string Error_800100190 {
            get {
                return ResourceManager.GetString("Error_800100190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (transaction in wrong state on aquirer side).
        /// </summary>
        public static string Error_800100191 {
            get {
                return ResourceManager.GetString("Error_800100191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid CVV, Amount has still been reserved on the customer&apos;s card and will be released in a few business days. Please ensure the CVV code is accurate before retrying the transaction).
        /// </summary>
        public static string Error_800100192 {
            get {
                return ResourceManager.GetString("Error_800100192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (UserAccount Number/ID unknown).
        /// </summary>
        public static string Error_800100195 {
            get {
                return ResourceManager.GetString("Error_800100195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (registration error).
        /// </summary>
        public static string Error_800100196 {
            get {
                return ResourceManager.GetString("Error_800100196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (registration cancelled externally).
        /// </summary>
        public static string Error_800100197 {
            get {
                return ResourceManager.GetString("Error_800100197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid holder).
        /// </summary>
        public static string Error_800100198 {
            get {
                return ResourceManager.GetString("Error_800100198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (invalid tax number).
        /// </summary>
        public static string Error_800100199 {
            get {
                return ResourceManager.GetString("Error_800100199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer to Payer due to reason not specified.
        /// </summary>
        public static string Error_800100200 {
            get {
                return ResourceManager.GetString("Error_800100200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or Bank Details Incorrect.
        /// </summary>
        public static string Error_800100201 {
            get {
                return ResourceManager.GetString("Error_800100201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Closed.
        /// </summary>
        public static string Error_800100202 {
            get {
                return ResourceManager.GetString("Error_800100202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Funds.
        /// </summary>
        public static string Error_800100203 {
            get {
                return ResourceManager.GetString("Error_800100203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandate Expired.
        /// </summary>
        public static string Error_800100204 {
            get {
                return ResourceManager.GetString("Error_800100204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandate Discarded.
        /// </summary>
        public static string Error_800100205 {
            get {
                return ResourceManager.GetString("Error_800100205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund of an authorized payment requested by the customer.
        /// </summary>
        public static string Error_800100206 {
            get {
                return ResourceManager.GetString("Error_800100206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund requested.
        /// </summary>
        public static string Error_800100207 {
            get {
                return ResourceManager.GetString("Error_800100207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct debit not enabled for the specified account or bank.
        /// </summary>
        public static string Error_800100208 {
            get {
                return ResourceManager.GetString("Error_800100208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC/bank account holder not valid.
        /// </summary>
        public static string Error_800100402 {
            get {
                return ResourceManager.GetString("Error_800100402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined (revocation of authorisation order).
        /// </summary>
        public static string Error_800100403 {
            get {
                return ResourceManager.GetString("Error_800100403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder has advised his bank to stop this recurring payment.
        /// </summary>
        public static string Error_800100500 {
            get {
                return ResourceManager.GetString("Error_800100500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder has advised his bank to stop all recurring payments for this merchant.
        /// </summary>
        public static string Error_800100501 {
            get {
                return ResourceManager.GetString("Error_800100501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Authentication Failed.
        /// </summary>
        public static string Error_Title_100380401 {
            get {
                return ResourceManager.GetString("Error_Title_100380401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Management transaction timed out.
        /// </summary>
        public static string Error_Title_100380501 {
            get {
                return ResourceManager.GetString("Error_Title_100380501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares Validation failed - problem with signature.
        /// </summary>
        public static string Error_Title_100390103 {
            get {
                return ResourceManager.GetString("Error_Title_100390103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejected because of technical error in 3DSecure system.
        /// </summary>
        public static string Error_Title_100390105 {
            get {
                return ResourceManager.GetString("Error_Title_100390105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously pending transactions timed out.
        /// </summary>
        public static string Error_Title_100396103 {
            get {
                return ResourceManager.GetString("Error_Title_100396103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot refund (refund volume exceeded or tx reversed or invalid workflow?).
        /// </summary>
        public static string Error_Title_800100151 {
            get {
                return ResourceManager.GetString("Error_Title_800100151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions declined by authorization system.
        /// </summary>
        public static string Error_Title_800100152 {
            get {
                return ResourceManager.GetString("Error_Title_800100152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions declined – Amount exceeds credit.
        /// </summary>
        public static string Error_Title_800100155 {
            get {
                return ResourceManager.GetString("Error_Title_800100155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions declined – Transactions not permitted.
        /// </summary>
        public static string Error_Title_800100170 {
            get {
                return ResourceManager.GetString("Error_Title_800100170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Transactions.
        /// </summary>
        public static string Error_Title_800110100 {
            get {
                return ResourceManager.GetString("Error_Title_800110100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (P-01)..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount sent to the bank is not equal the received amount.
        /// </summary>
        public static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment process failed.
        /// </summary>
        public static string InvalidPayment {
            get {
                return ResourceManager.GetString("InvalidPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not in a valid status.
        /// </summary>
        public static string InvalidRequestStatus {
            get {
                return ResourceManager.GetString("InvalidRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy was purchased before.
        /// </summary>
        public static string PolicyPurchasedBefore {
            get {
                return ResourceManager.GetString("PolicyPurchasedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request was cancelled.
        /// </summary>
        public static string RequestIsCancelled {
            get {
                return ResourceManager.GetString("RequestIsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was done successfully, policy will be sent shortly.
        /// </summary>
        public static string SuccessPayment {
            get {
                return ResourceManager.GetString("SuccessPayment", resourceCulture);
            }
        }
    }
}
