//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Inquiry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitInquiryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitInquiryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Inquiry.SubmitInquiryResource", typeof(SubmitInquiryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking this additional driver {0} in NIC. Please try again later.
        /// </summary>
        public static string AdditionalDriverYakeenError {
            get {
                return ResourceManager.GetString("AdditionalDriverYakeenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy effective date should be within 30 days starts from toworrow.
        /// </summary>
        public static string autoleasing_InvalidPolicyEffectiveDate {
            get {
                return ResourceManager.GetString("autoleasing_InvalidPolicyEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id {0} is blocked, Please Contact Customer Service 8001180044.
        /// </summary>
        public static string BlockedNin {
            get {
                return ResourceManager.GetString("BlockedNin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select children below 16.
        /// </summary>
        public static string ChildrenBelow16YearsIsNull {
            get {
                return ResourceManager.GetString("ChildrenBelow16YearsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city code..
        /// </summary>
        public static string CityCodeRequired {
            get {
                return ResourceManager.GetString("CityCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company driver exceeds insurance number limit per year: 5.
        /// </summary>
        public static string CompanyDriverExceedsInsuranceNumberLimitPerYear {
            get {
                return ResourceManager.GetString("CompanyDriverExceedsInsuranceNumberLimitPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main driver is assigned to another company.
        /// </summary>
        public static string CompanyDriverIsAssignedToAnotherCompany {
            get {
                return ResourceManager.GetString("CompanyDriverIsAssignedToAnotherCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter custom card..
        /// </summary>
        public static string CustomCardRequired {
            get {
                return ResourceManager.GetString("CustomCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another quotation for the main driver related to another ensured, and the quotation expires within {0} hours.
        /// </summary>
        public static string DriverHasEdaatValidRequest {
            get {
                return ResourceManager.GetString("DriverHasEdaatValidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select number of accidents In last 5 years.
        /// </summary>
        public static string DriverNOALast5YearsIsNull {
            get {
                return ResourceManager.GetString("DriverNOALast5YearsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select number of accidents In last 5 years for driver {0}.
        /// </summary>
        public static string DriverNOALast5YearsIsNullAdditionalDriver {
            get {
                return ResourceManager.GetString("DriverNOALast5YearsIsNullAdditionalDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Percentage exceeded 100%.
        /// </summary>
        public static string DrivingPercentageErrorInvalid {
            get {
                return ResourceManager.GetString("DrivingPercentageErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Percentage less than 100%.
        /// </summary>
        public static string DrivingPercentageLessThan100 {
            get {
                return ResourceManager.GetString("DrivingPercentageLessThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your education qualification.
        /// </summary>
        public static string EducationIdIsNull {
            get {
                return ResourceManager.GetString("EducationIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your education qualification for driver {0}.
        /// </summary>
        public static string EducationIdIsNullAdditionalDriver {
            get {
                return ResourceManager.GetString("EducationIdIsNullAdditionalDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (I-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (H-01).
        /// </summary>
        public static string ErrorHashing {
            get {
                return ResourceManager.GetString("ErrorHashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You exceeded the allowed number of policies.
        /// </summary>
        public static string exceededLimit {
            get {
                return ResourceManager.GetString("exceededLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired captcha..
        /// </summary>
        public static string ExpiredCaptcha {
            get {
                return ResourceManager.GetString("ExpiredCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance company Id is null.
        /// </summary>
        public static string insuranceCompanyId {
            get {
                return ResourceManager.GetString("insuranceCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can&apos;t transfer ownership to your self.
        /// </summary>
        public static string InvaildOldOwnerNin {
            get {
                return ResourceManager.GetString("InvaildOldOwnerNin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha..
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is Invalid Please Enter Correct Data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id for main driver is not correct.
        /// </summary>
        public static string InvalidMainDriverNinWith700 {
            get {
                return ResourceManager.GetString("InvalidMainDriverNinWith700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD request is onvalid, as TPL policy expiry date less than 90 days.
        /// </summary>
        public static string InvalidODPolicyExpiryDate {
            get {
                return ResourceManager.GetString("InvalidODPolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy effective date should be within 29 days starts from toworrow.
        /// </summary>
        public static string InvalidPolicyEffectiveDate {
            get {
                return ResourceManager.GetString("InvalidPolicyEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy effective date should starts from toworrow and should not exceed 30/06/2020.
        /// </summary>
        public static string InvalidPolicyEffectiveDateToEndOfJune {
            get {
                return ResourceManager.GetString("InvalidPolicyEffectiveDateToEndOfJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Driver For Company Not Exist.
        /// </summary>
        public static string MainDriverForCompanyNotExist {
            get {
                return ResourceManager.GetString("MainDriverForCompanyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select driver medical condition.
        /// </summary>
        public static string MedicalConditionIdIsNull {
            get {
                return ResourceManager.GetString("MedicalConditionIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select driver medical condition for driver {0}.
        /// </summary>
        public static string MedicalConditionIdIsNullAdditionalDriver {
            get {
                return ResourceManager.GetString("MedicalConditionIdIsNullAdditionalDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vehicle expected KM annually.
        /// </summary>
        public static string MileageExpectedAnnualIdIsNull {
            get {
                return ResourceManager.GetString("MileageExpectedAnnualIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As per SAMA regulations, National Address is mandatory when issuing the policy and for any types of insurance, Register now from 
        /// &lt;a href=&quot;https://register.address.gov.sa/ar/default.aspx&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string MissingAddress {
            get {
                return ResourceManager.GetString("MissingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number can&apos;t be empty.
        /// </summary>
        public static string MobileNumberIsEmpty {
            get {
                return ResourceManager.GetString("MobileNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Driver Mobile Number Is Not Valid.
        /// </summary>
        public static string MobileNumberNotValid {
            get {
                return ResourceManager.GetString("MobileNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter national id.
        /// </summary>
        public static string NationalIdIsNull {
            get {
                return ResourceManager.GetString("NationalIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter national Id..
        /// </summary>
        public static string NationalIdRequired {
            get {
                return ResourceManager.GetString("NationalIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no quotation request with the given external id.
        /// </summary>
        public static string NoQuotation {
            get {
                return ResourceManager.GetString("NoQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is outdated, please update the application.
        /// </summary>
        public static string OldMobileVersion {
            get {
                return ResourceManager.GetString("OldMobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vehicle overnight parking location.
        /// </summary>
        public static string ParkingLocationIdIsNull {
            get {
                return ResourceManager.GetString("ParkingLocationIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter policy effective date Id..
        /// </summary>
        public static string PolicyEffectiveDateRequired {
            get {
                return ResourceManager.GetString("PolicyEffectiveDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Is Empty.
        /// </summary>
        public static string RequestModelIsNullException {
            get {
                return ResourceManager.GetString("RequestModelIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error occured while checking the national address, Please try again later.
        /// </summary>
        public static string SaudiPostError {
            get {
                return ResourceManager.GetString("SaudiPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID Number {0} format is not valid in Saudi Post.
        /// </summary>
        public static string SaudiPostInvalidPublicID {
            get {
                return ResourceManager.GetString("SaudiPostInvalidPublicID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sequence number..
        /// </summary>
        public static string SequenceNumberRequired {
            get {
                return ResourceManager.GetString("SequenceNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select transmission type.
        /// </summary>
        public static string TransmissionTypeIdIsNull {
            get {
                return ResourceManager.GetString("TransmissionTypeIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle exceeded the maximum allowed limit for today, go to profile page to see price list for today.
        /// </summary>
        public static string VehicleExceededLimit {
            get {
                return ResourceManager.GetString("VehicleExceededLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vehicleId type..
        /// </summary>
        public static string VehicleIdTypeIdRequired {
            get {
                return ResourceManager.GetString("VehicleIdTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter vehicle owner national id.
        /// </summary>
        public static string VehicleOwnerNinIsNull {
            get {
                return ResourceManager.GetString("VehicleOwnerNinIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid vehicle value it should not be less than 10K SAR.
        /// </summary>
        public static string VehicleValueLessThan10K {
            get {
                return ResourceManager.GetString("VehicleValueLessThan10K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Input Captcha.
        /// </summary>
        public static string WrongInputCaptcha {
            get {
                return ResourceManager.GetString("WrongInputCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number Not Found at NIC.
        /// </summary>
        public static string YakeenError_1 {
            get {
                return ResourceManager.GetString("YakeenError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Border Number Is Not Found at NIC.
        /// </summary>
        public static string YakeenError_10 {
            get {
                return ResourceManager.GetString("YakeenError_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred while processing your request. Please try again later.
        /// </summary>
        public static string YakeenError_100 {
            get {
                return ResourceManager.GetString("YakeenError_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Number Not Found at Saudi Post Records.
        /// </summary>
        public static string YakeenError_11 {
            get {
                return ResourceManager.GetString("YakeenError_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number format is not valid.
        /// </summary>
        public static string YakeenError_12 {
            get {
                return ResourceManager.GetString("YakeenError_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_13 {
            get {
                return ResourceManager.GetString("YakeenError_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_14 {
            get {
                return ResourceManager.GetString("YakeenError_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Iqama Number format is not valid.
        /// </summary>
        public static string YakeenError_15 {
            get {
                return ResourceManager.GetString("YakeenError_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_16 {
            get {
                return ResourceManager.GetString("YakeenError_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_17 {
            get {
                return ResourceManager.GetString("YakeenError_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date does not match NIC records.
        /// </summary>
        public static string YakeenError_18 {
            get {
                return ResourceManager.GetString("YakeenError_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date does not match NIC records.
        /// </summary>
        public static string YakeenError_19 {
            get {
                return ResourceManager.GetString("YakeenError_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Iqama Number Is Not Found at NIC.
        /// </summary>
        public static string YakeenError_2 {
            get {
                return ResourceManager.GetString("YakeenError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_20 {
            get {
                return ResourceManager.GetString("YakeenError_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Owner ID format is not valid.
        /// </summary>
        public static string YakeenError_21 {
            get {
                return ResourceManager.GetString("YakeenError_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sequence Number format is not valid.
        /// </summary>
        public static string YakeenError_22 {
            get {
                return ResourceManager.GetString("YakeenError_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID does not match NIC records.
        /// </summary>
        public static string YakeenError_23 {
            get {
                return ResourceManager.GetString("YakeenError_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SequenceNumber format is not valid.
        /// </summary>
        public static string YakeenError_24 {
            get {
                return ResourceManager.GetString("YakeenError_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year does not match NIC records.
        /// </summary>
        public static string YakeenError_25 {
            get {
                return ResourceManager.GetString("YakeenError_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year does not match NIC records.
        /// </summary>
        public static string YakeenError_26 {
            get {
                return ResourceManager.GetString("YakeenError_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sponsor Number format is not valid.
        /// </summary>
        public static string YakeenError_27 {
            get {
                return ResourceManager.GetString("YakeenError_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_28 {
            get {
                return ResourceManager.GetString("YakeenError_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_29 {
            get {
                return ResourceManager.GetString("YakeenError_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string YakeenError_3 {
            get {
                return ResourceManager.GetString("YakeenError_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID does not match NIC records.
        /// </summary>
        public static string YakeenError_30 {
            get {
                return ResourceManager.GetString("YakeenError_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_31 {
            get {
                return ResourceManager.GetString("YakeenError_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_32 {
            get {
                return ResourceManager.GetString("YakeenError_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor does not match NIC records.
        /// </summary>
        public static string YakeenError_33 {
            get {
                return ResourceManager.GetString("YakeenError_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent ID does not match NIC records.
        /// </summary>
        public static string YakeenError_34 {
            get {
                return ResourceManager.GetString("YakeenError_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Border Number format is not valid.
        /// </summary>
        public static string YakeenError_35 {
            get {
                return ResourceManager.GetString("YakeenError_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_36 {
            get {
                return ResourceManager.GetString("YakeenError_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent ID does not match NIC records.
        /// </summary>
        public static string YakeenError_37 {
            get {
                return ResourceManager.GetString("YakeenError_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent ID does not match NIC records.
        /// </summary>
        public static string YakeenError_38 {
            get {
                return ResourceManager.GetString("YakeenError_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_39 {
            get {
                return ResourceManager.GetString("YakeenError_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address Language format is not valid.
        /// </summary>
        public static string YakeenError_40 {
            get {
                return ResourceManager.GetString("YakeenError_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Birth Date format is not valid.
        /// </summary>
        public static string YakeenError_41 {
            get {
                return ResourceManager.GetString("YakeenError_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date format is not valid.
        /// </summary>
        public static string YakeenError_42 {
            get {
                return ResourceManager.GetString("YakeenError_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_43 {
            get {
                return ResourceManager.GetString("YakeenError_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth does not match NIC records.
        /// </summary>
        public static string YakeenError_44 {
            get {
                return ResourceManager.GetString("YakeenError_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date does not match NIC records.
        /// </summary>
        public static string YakeenError_45 {
            get {
                return ResourceManager.GetString("YakeenError_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date does not match NIC records.
        /// </summary>
        public static string YakeenError_48 {
            get {
                return ResourceManager.GetString("YakeenError_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence number not found in NIC.
        /// </summary>
        public static string YakeenError_5 {
            get {
                return ResourceManager.GetString("YakeenError_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom card not found in NIC.
        /// </summary>
        public static string YakeenError_6 {
            get {
                return ResourceManager.GetString("YakeenError_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama Number Not Found at NIC.
        /// </summary>
        public static string YakeenError_7 {
            get {
                return ResourceManager.GetString("YakeenError_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passport Number Is Not Found at NIC.
        /// </summary>
        public static string YakeenError_8 {
            get {
                return ResourceManager.GetString("YakeenError_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passport Number Is Not Found at NIC.
        /// </summary>
        public static string YakeenError_9 {
            get {
                return ResourceManager.GetString("YakeenError_9", resourceCulture);
            }
        }
    }
}
