//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Integration.Providers.Wataniya.MappingResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Colors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Colors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Integration.Providers.Wataniya.MappingResources.Colors", typeof(Colors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ابيض {
            get {
                return ResourceManager.GetString("ابيض", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string أحمر {
            get {
                return ResourceManager.GetString("أحمر", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string أحمر_غامق {
            get {
                return ResourceManager.GetString("أحمر غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string أحمر_فاتح {
            get {
                return ResourceManager.GetString("أحمر فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        public static string اخضر {
            get {
                return ResourceManager.GetString("اخضر", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string اخضر_ذهبي {
            get {
                return ResourceManager.GetString("اخضر ذهبي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string اخضر_غامق {
            get {
                return ResourceManager.GetString("اخضر غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string اخضر_فاتح {
            get {
                return ResourceManager.GetString("اخضر فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        public static string أرجواني {
            get {
                return ResourceManager.GetString("أرجواني", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string ازرق {
            get {
                return ResourceManager.GetString("ازرق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        public static string ازرق_سماوي {
            get {
                return ResourceManager.GetString("ازرق سماوي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string ازرق_غامق {
            get {
                return ResourceManager.GetString("ازرق غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string ازرق_فاتح {
            get {
                return ResourceManager.GetString("ازرق فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string اسود {
            get {
                return ResourceManager.GetString("اسود", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        public static string اصفر {
            get {
                return ResourceManager.GetString("اصفر", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        public static string اصفر_غامق {
            get {
                return ResourceManager.GetString("اصفر غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        public static string اصفر_فاتح {
            get {
                return ResourceManager.GetString("اصفر فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string برتقالي {
            get {
                return ResourceManager.GetString("برتقالي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string برتقالي_غامق {
            get {
                return ResourceManager.GetString("برتقالي غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string برتقالي_فاتح {
            get {
                return ResourceManager.GetString("برتقالي فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.
        /// </summary>
        public static string برونزي {
            get {
                return ResourceManager.GetString("برونزي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string بنفسجي {
            get {
                return ResourceManager.GetString("بنفسجي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string بنفسجي_غامق {
            get {
                return ResourceManager.GetString("بنفسجي غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string بنفسجي_فاتح {
            get {
                return ResourceManager.GetString("بنفسجي فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string بني {
            get {
                return ResourceManager.GetString("بني", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string بني_غامق {
            get {
                return ResourceManager.GetString("بني غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string بني_فاتح {
            get {
                return ResourceManager.GetString("بني فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string بيج {
            get {
                return ResourceManager.GetString("بيج", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string بيج_غامق {
            get {
                return ResourceManager.GetString("بيج غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        public static string بيج_فاتح {
            get {
                return ResourceManager.GetString("بيج فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        public static string حليبي {
            get {
                return ResourceManager.GetString("حليبي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string ذهبي {
            get {
                return ResourceManager.GetString("ذهبي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string ذهبي_غامق {
            get {
                return ResourceManager.GetString("ذهبي غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string ذهبي_فاتح {
            get {
                return ResourceManager.GetString("ذهبي فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string رصاصي {
            get {
                return ResourceManager.GetString("رصاصي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string رصاصي_غامق {
            get {
                return ResourceManager.GetString("رصاصي غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string رصاصي_فاتح {
            get {
                return ResourceManager.GetString("رصاصي فاتح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string رمادي {
            get {
                return ResourceManager.GetString("رمادي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        public static string رملي {
            get {
                return ResourceManager.GetString("رملي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        public static string زهري {
            get {
                return ResourceManager.GetString("زهري", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        public static string زيتوني {
            get {
                return ResourceManager.GetString("زيتوني", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string زيعي {
            get {
                return ResourceManager.GetString("زيعي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        public static string سماوي {
            get {
                return ResourceManager.GetString("سماوي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56.
        /// </summary>
        public static string صحراوي {
            get {
                return ResourceManager.GetString("صحراوي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string صدفي {
            get {
                return ResourceManager.GetString("صدفي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        public static string عسلي {
            get {
                return ResourceManager.GetString("عسلي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        public static string عنابي {
            get {
                return ResourceManager.GetString("عنابي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        public static string عنابي_وذهبي {
            get {
                return ResourceManager.GetString("عنابي وذهبي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string عودي {
            get {
                return ResourceManager.GetString("عودي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57.
        /// </summary>
        public static string فستقي {
            get {
                return ResourceManager.GetString("فستقي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string فضي {
            get {
                return ResourceManager.GetString("فضي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string كحلي {
            get {
                return ResourceManager.GetString("كحلي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        public static string لون_الدوريات {
            get {
                return ResourceManager.GetString("لون الدوريات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string وردي {
            get {
                return ResourceManager.GetString("وردي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string وردي_غامق {
            get {
                return ResourceManager.GetString("وردي غامق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string وردي_فاتح {
            get {
                return ResourceManager.GetString("وردي فاتح", resourceCulture);
            }
        }
    }
}
