//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamkeen.bll {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnifiedTextForEnglishAndArabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnifiedTextForEnglishAndArabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tamkeen.bll.UnifiedTextForEnglishAndArabic", typeof(UnifiedTextForEnglishAndArabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر الاضافي.
        /// </summary>
        internal static string Additional_age_Ar {
            get {
                return ResourceManager.GetString("Additional_age_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional age.
        /// </summary>
        internal static string Additional_age_En {
            get {
                return ResourceManager.GetString("Additional_age_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصاريف الاضافيه.
        /// </summary>
        internal static string Additional_expenses_Ar {
            get {
                return ResourceManager.GetString("Additional_expenses_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional_expenses.
        /// </summary>
        internal static string Additional_expenses_En {
            get {
                return ResourceManager.GetString("Additional_expenses_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )الحوادث بسبب )إضافي تحمي.
        /// </summary>
        internal static string additional_price_Ar {
            get {
                return ResourceManager.GetString("additional_price_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Accidents due to) additional protection.
        /// </summary>
        internal static string additional_price_En {
            get {
                return ResourceManager.GetString("additional_price_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم عدم وجود مطالبات.
        /// </summary>
        internal static string Discount_no_claims_Ar {
            get {
                return ResourceManager.GetString("Discount_no_claims_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount no claims.
        /// </summary>
        internal static string Discount_no_claims_En {
            get {
                return ResourceManager.GetString("Discount_no_claims_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسط الاضافي.
        /// </summary>
        internal static string Extra_Premium_Ar {
            get {
                return ResourceManager.GetString("Extra_Premium_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Premium.
        /// </summary>
        internal static string Extra_Premium_En {
            get {
                return ResourceManager.GetString("Extra_Premium_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم الولاء.
        /// </summary>
        internal static string loyalty_Discount_Ar {
            get {
                return ResourceManager.GetString("loyalty_Discount_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loyalty Discount.
        /// </summary>
        internal static string loyalty_Discount_En {
            get {
                return ResourceManager.GetString("loyalty_Discount_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم خاص.
        /// </summary>
        internal static string Special_Discount_Ar {
            get {
                return ResourceManager.GetString("Special_Discount_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Discount.
        /// </summary>
        internal static string Special_Discount_En {
            get {
                return ResourceManager.GetString("Special_Discount_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبه قيمة المضافه.
        /// </summary>
        internal static string VAT_Tax_Ar {
            get {
                return ResourceManager.GetString("VAT_Tax_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string VAT_Tax_En {
            get {
                return ResourceManager.GetString("VAT_Tax_En", resourceCulture);
            }
        }
    }
}
