//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Inquiry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NajmExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NajmExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Inquiry.NajmExceptionResource", typeof(NajmExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate policy holder ID is not allowed in Najm.
        /// </summary>
        public static string CorporatePolicyHolderIDIsNOTAllowed {
            get {
                return ResourceManager.GetString("CorporatePolicyHolderIDIsNOTAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credential.
        /// </summary>
        public static string E101 {
            get {
                return ResourceManager.GetString("E101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Don&apos;t have permission to access.
        /// </summary>
        public static string E102 {
            get {
                return ResourceManager.GetString("E102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver ID must have data.
        /// </summary>
        public static string E103 {
            get {
                return ResourceManager.GetString("E103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string E104 {
            get {
                return ResourceManager.GetString("E104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration type is not valid.
        /// </summary>
        public static string E105 {
            get {
                return ResourceManager.GetString("E105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Plate number is not valid.
        /// </summary>
        public static string E106 {
            get {
                return ResourceManager.GetString("E106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Id is invalid.
        /// </summary>
        public static string E107 {
            get {
                return ResourceManager.GetString("E107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Vehicle plate number.
        /// </summary>
        public static string E108 {
            get {
                return ResourceManager.GetString("E108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Vehicle plate number or Sequence number.
        /// </summary>
        public static string E109 {
            get {
                return ResourceManager.GetString("E109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in processing request for Active policy.
        /// </summary>
        public static string E110 {
            get {
                return ResourceManager.GetString("E110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle sequence number is not valid.
        /// </summary>
        public static string E111 {
            get {
                return ResourceManager.GetString("E111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate request found, try after some time.
        /// </summary>
        public static string E112 {
            get {
                return ResourceManager.GetString("E112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver ID is invalid.
        /// </summary>
        public static string E113 {
            get {
                return ResourceManager.GetString("E113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while processing your request in Najm.
        /// </summary>
        public static string ErrorInprocessingYourRequest {
            get {
                return ResourceManager.GetString("ErrorInprocessingYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while checking this additional driver {0} with Najm. Please try again later.
        /// </summary>
        public static string GeneralAdditionalDriverError {
            get {
                return ResourceManager.GetString("GeneralAdditionalDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while checking insured information with Najm. Please try again later.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately error occur please try later.
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Najm credential.
        /// </summary>
        public static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid policy holder ID in Najm.
        /// </summary>
        public static string InvalidPolicyholderID {
            get {
                return ResourceManager.GetString("InvalidPolicyholderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid this policy holder ID {0} in Najm.
        /// </summary>
        public static string InvalidPolicyholderIDAdditionalDriver {
            get {
                return ResourceManager.GetString("InvalidPolicyholderIDAdditionalDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Vehicle ID in Najm.
        /// </summary>
        public static string InvalidVehicleID {
            get {
                return ResourceManager.GetString("InvalidVehicleID", resourceCulture);
            }
        }
    }
}
