//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VerificationCodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationCodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Account.VerificationCodeResource", typeof(VerificationCodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminOTP:.
        /// </summary>
        public static string OtpSmsBody_Admin {
            get {
                return ResourceManager.GetString("OtpSmsBody_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckoutOtp:.
        /// </summary>
        public static string OtpSmsBody_Checkout {
            get {
                return ResourceManager.GetString("OtpSmsBody_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalOTP:.
        /// </summary>
        public static string OtpSmsBody_Portal {
            get {
                return ResourceManager.GetString("OtpSmsBody_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishPhoneCodeMessage.
        /// </summary>
        public static string SmsTwoFactorCodeProviderName {
            get {
                return ResourceManager.GetString("SmsTwoFactorCodeProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string VerifyCode_Failed {
            get {
                return ResourceManager.GetString("VerifyCode_Failed", resourceCulture);
            }
        }
    }
}
