//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.UserTicket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserTicketResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserTicketResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.UserTicket.UserTicketResources", typeof(UserTicketResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAttachment.
        /// </summary>
        public static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Name.
        /// </summary>
        public static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Invoice.
        /// </summary>
        public static string ChooseInvoice {
            get {
                return ResourceManager.GetString("ChooseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Policy.
        /// </summary>
        public static string ChoosePolicy {
            get {
                return ResourceManager.GetString("ChoosePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Ticket Type.
        /// </summary>
        public static string ChooseTicketType {
            get {
                return ResourceManager.GetString("ChooseTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Vehicle.
        /// </summary>
        public static string ChooseVehicle {
            get {
                return ResourceManager.GetString("ChooseVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty User Email.
        /// </summary>
        public static string EmptyUserEmail {
            get {
                return ResourceManager.GetString("EmptyUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (UT-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        public static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company Name.
        /// </summary>
        public static string InsuranceCompanyName {
            get {
                return ResourceManager.GetString("InsuranceCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Channel.
        /// </summary>
        public static string InvalidChannel {
            get {
                return ResourceManager.GetString("InvalidChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Policy/Invoice Number.
        /// </summary>
        public static string InvalidExtraData {
            get {
                return ResourceManager.GetString("InvalidExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIN is Empty.
        /// </summary>
        public static string InvalidNIN {
            get {
                return ResourceManager.GetString("InvalidNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ticket Type.
        /// </summary>
        public static string InvalidTicketType {
            get {
                return ResourceManager.GetString("InvalidTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Notes is Empty.
        /// </summary>
        public static string InvalidUserNotes {
            get {
                return ResourceManager.GetString("InvalidUserNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice not belongs to the User.
        /// </summary>
        public static string InvoiceIdNotBelongsToThisUser {
            get {
                return ResourceManager.GetString("InvoiceIdNotBelongsToThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Not Found.
        /// </summary>
        public static string InvoicesNotFound {
            get {
                return ResourceManager.GetString("InvoicesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should open ticket after 24 hours from pruchase date.
        /// </summary>
        public static string NajmPolicyIssuedBefore24hours {
            get {
                return ResourceManager.GetString("NajmPolicyIssuedBefore24hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment added to ticket number #{0}.
        /// </summary>
        public static string NewReplyAdded {
            get {
                return ResourceManager.GetString("NewReplyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        public static string NewTicket {
            get {
                return ResourceManager.GetString("NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string Nin {
            get {
                return ResourceManager.GetString("Nin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an opened ticked for this National ID ({0}), with ticket number: {1}.
        /// </summary>
        public static string OpenedTicketExistsForNIN {
            get {
                return ResourceManager.GetString("OpenedTicketExistsForNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an opened ticked for this Sequence/Custom Number ({0}), with ticket number: {1}.
        /// </summary>
        public static string OpenedTicketExistsForSequenceOrCustomCardNumber {
            get {
                return ResourceManager.GetString("OpenedTicketExistsForSequenceOrCustomCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polices Not Found.
        /// </summary>
        public static string PolicesNotFound {
            get {
                return ResourceManager.GetString("PolicesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy or Sequence/Custom Number not belongs to the User.
        /// </summary>
        public static string PolicyIdNotBelongsToThisUser {
            get {
                return ResourceManager.GetString("PolicyIdNotBelongsToThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string PolicyNo {
            get {
                return ResourceManager.GetString("PolicyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Created.
        /// </summary>
        public static string PopupTicketCreated {
            get {
                return ResourceManager.GetString("PopupTicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Creation Failed.
        /// </summary>
        public static string PopupTicketCreationFailed {
            get {
                return ResourceManager.GetString("PopupTicketCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence/Custom Card Number.
        /// </summary>
        public static string SequenceOrCustomCardNumber {
            get {
                return ResourceManager.GetString("SequenceOrCustomCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Ticket.
        /// </summary>
        public static string SubmitTicket {
            get {
                return ResourceManager.GetString("SubmitTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string SubmittingTicketLoading {
            get {
                return ResourceManager.GetString("SubmittingTicketLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number #{0} is closed.
        /// </summary>
        public static string TicketClosed {
            get {
                return ResourceManager.GetString("TicketClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number.
        /// </summary>
        public static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are glad to serve you...
        ///&lt;br&gt;&lt;br&gt;
        ///Ticket raised with nubber #{0} and we are working on it...
        ///&lt;br&gt;
        ///You can follow the status of your ticket in the &quot;Notification&quot; menu.
        ///&lt;br&gt;
        ///#Bcare_cares.
        /// </summary>
        public static string TicketReplyMessage {
            get {
                return ResourceManager.GetString("TicketReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Type.
        /// </summary>
        public static string TicketType {
            get {
                return ResourceManager.GetString("TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of letters is {0} letter.
        /// </summary>
        public static string UserNotesMaxLength {
            get {
                return ResourceManager.GetString("UserNotesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ticket was created with number #{0}.
        /// </summary>
        public static string UserTicketCreated {
            get {
                return ResourceManager.GetString("UserTicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ticket was created with number #{0} By Customer Service.
        /// </summary>
        public static string UserTicketCreatedByCustomerService {
            get {
                return ResourceManager.GetString("UserTicketCreatedByCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        public static string VehicleName {
            get {
                return ResourceManager.GetString("VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Found.
        /// </summary>
        public static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
    }
}
