//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Promotions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PromotionProgramResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromotionProgramResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Promotions.PromotionProgramResource", typeof(PromotionProgramResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not Exist.
        /// </summary>
        public static string AddressNotExist {
            get {
                return ResourceManager.GetString("AddressNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the file, please try again later.
        /// </summary>
        public static string Attachment_serviceException {
            get {
                return ResourceManager.GetString("Attachment_serviceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully and waiting for admin approve.
        /// </summary>
        public static string Attachment_Success {
            get {
                return ResourceManager.GetString("Attachment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This National Id Can&apos;t join this program..
        /// </summary>
        public static string CanNotJoinProgramBuNin {
            get {
                return ResourceManager.GetString("CanNotJoinProgramBuNin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is required.
        /// </summary>
        public static string CaptchaEmpty {
            get {
                return ResourceManager.GetString("CaptchaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Captcha.
        /// </summary>
        public static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are confirmed to join the program..
        /// </summary>
        public static string ConfirmJoinProgram_EmailAlreadyConfirmedBefore {
            get {
                return ResourceManager.GetString("ConfirmJoinProgram_EmailAlreadyConfirmedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user didn&apos;t request to join this promotion program.
        /// </summary>
        public static string ConfirmJoinProgram_EmailDoesNotHaveRequest {
            get {
                return ResourceManager.GetString("ConfirmJoinProgram_EmailDoesNotHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can not be null when confirm join program.
        /// </summary>
        public static string ConfirmJoinProgram_EmailEmpty {
            get {
                return ResourceManager.GetString("ConfirmJoinProgram_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion program id is invalid when confirm join program.
        /// </summary>
        public static string ConfirmJoinProgram_InvalidProgramId {
            get {
                return ResourceManager.GetString("ConfirmJoinProgram_InvalidProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to join the program has been expired..
        /// </summary>
        public static string ConfirmJoinProgramRequestExpired {
            get {
                return ResourceManager.GetString("ConfirmJoinProgramRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Card Number is empty.
        /// </summary>
        public static string CustomNumberEmpty {
            get {
                return ResourceManager.GetString("CustomNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while disenroll you from the program, please try again..
        /// </summary>
        public static string DisenrollUserErrorHappen {
            get {
                return ResourceManager.GetString("DisenrollUserErrorHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in wrong format.
        /// </summary>
        public static string Email_Format_Erorr {
            get {
                return ResourceManager.GetString("Email_Format_Erorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already used by another user..
        /// </summary>
        public static string EmailAlreadyUsedByAnotherUser {
            get {
                return ResourceManager.GetString("EmailAlreadyUsedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your profile, since you already joined to an program.
        /// </summary>
        public static string emailJoinedFromProfile {
            get {
                return ResourceManager.GetString("emailJoinedFromProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is joined to program with another nationa id.
        /// </summary>
        public static string emailJoinedWithAnotherNin {
            get {
                return ResourceManager.GetString("emailJoinedWithAnotherNin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All model data is empty.
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is empty ( {0} ).
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to upload, please upload file.
        /// </summary>
        public static string emptyFile {
            get {
                return ResourceManager.GetString("emptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is empty.
        /// </summary>
        public static string EmptyUserId {
            get {
                return ResourceManager.GetString("EmptyUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (V-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An occurred while joining the program, and the error is: {0}.
        /// </summary>
        public static string ErrorWhileJoiningPromotionProgram {
            get {
                return ResourceManager.GetString("ErrorWhileJoiningPromotionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size limit exceeded, Max file size is {0} MB.
        /// </summary>
        public static string fileSizeLimitExceeded {
            get {
                return ResourceManager.GetString("fileSizeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Card Number is not valid.
        /// </summary>
        public static string InvalidCustomNumber {
            get {
                return ResourceManager.GetString("InvalidCustomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Extension, allowed extensions are ( {0} ).
        /// </summary>
        public static string invalidFileExtension {
            get {
                return ResourceManager.GetString("invalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalId  is not valid.
        /// </summary>
        public static string InvalidNationalId {
            get {
                return ResourceManager.GetString("InvalidNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number  is not valid.
        /// </summary>
        public static string InvalidSequenceNumber {
            get {
                return ResourceManager.GetString("InvalidSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JoinProgramConfirmationBody {
            get {
                return ResourceManager.GetString("JoinProgramConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Promotion Program Confirmation.
        /// </summary>
        public static string JoinProgramConfirmationSubject {
            get {
                return ResourceManager.GetString("JoinProgramConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are confirmed to join the program..
        /// </summary>
        public static string JoinProgramIsConfirmed {
            get {
                return ResourceManager.GetString("JoinProgramIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Confirmation e-mail has been sent to your email, please check it to continue joining the promotion program..
        /// </summary>
        public static string JoinProgramMailSent {
            get {
                return ResourceManager.GetString("JoinProgramMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the allowed tries, please try in 5 minutes..
        /// </summary>
        public static string LoginUserPartialLock {
            get {
                return ResourceManager.GetString("LoginUserPartialLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id is empty.
        /// </summary>
        public static string NationalIdEmpty {
            get {
                return ResourceManager.GetString("NationalIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This National Id already assigned to the program: {1}..
        /// </summary>
        public static string NinAlreadyJoinedToProgram {
            get {
                return ResourceManager.GetString("NinAlreadyJoinedToProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This National Id Can&apos;t join this program, because he assigned to the program: {0}..
        /// </summary>
        public static string NinAlreadyJoinedToProgram_error {
            get {
                return ResourceManager.GetString("NinAlreadyJoinedToProgram_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to see data in this page.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This national id not enrolled in any promotion program.
        /// </summary>
        public static string NullResult {
            get {
                return ResourceManager.GetString("NullResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id can&apos;t be less than 1.
        /// </summary>
        public static string ProgramIdInvalid {
            get {
                return ResourceManager.GetString("ProgramIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find program with this is id: {0}..
        /// </summary>
        public static string ProgramNotFound {
            get {
                return ResourceManager.GetString("ProgramNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No promotion attachemnt with this id: {0}.
        /// </summary>
        public static string PromotionAttachmentNotFound {
            get {
                return ResourceManager.GetString("PromotionAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No promotion with this id: {0}.
        /// </summary>
        public static string PromotionNotFound {
            get {
                return ResourceManager.GetString("PromotionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the file, please try again later.
        /// </summary>
        public static string ReadFile_ServiceException {
            get {
                return ResourceManager.GetString("ReadFile_ServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deserving discount.
        /// </summary>
        public static string ResultEmptyForWareefDiscount {
            get {
                return ResourceManager.GetString("ResultEmptyForWareefDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Not found Any Record Against That Tracking Id.
        /// </summary>
        public static string SCAResponseCode_03 {
            get {
                return ResourceManager.GetString("SCAResponseCode_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user did not sign up for membership yet.
        /// </summary>
        public static string SCAResponseCode_04 {
            get {
                return ResourceManager.GetString("SCAResponseCode_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user membership is expired.
        /// </summary>
        public static string SCAResponseCode_06 {
            get {
                return ResourceManager.GetString("SCAResponseCode_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contractor is not relevant with our organization activities.
        /// </summary>
        public static string SCAResponseCode_07 {
            get {
                return ResourceManager.GetString("SCAResponseCode_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend while sending confirmation email..
        /// </summary>
        public static string SendingConfirmationEmail {
            get {
                return ResourceManager.GetString("SendingConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number is empty.
        /// </summary>
        public static string SequenceNumberEmpty {
            get {
                return ResourceManager.GetString("SequenceNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend, please try again later.
        /// </summary>
        public static string ServiceException {
            get {
                return ResourceManager.GetString("ServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded, and wating for confirmation by admin.
        /// </summary>
        public static string Success_Attachment {
            get {
                return ResourceManager.GetString("Success_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This domain not active.
        /// </summary>
        public static string thisdomainnotactive {
            get {
                return ResourceManager.GetString("thisdomainnotactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token key is null.
        /// </summary>
        public static string TokenEmpty {
            get {
                return ResourceManager.GetString("TokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success and wait to approved by admin.
        /// </summary>
        public static string UploadAttacmentsSuccess {
            get {
                return ResourceManager.GetString("UploadAttacmentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This uer already joined a promotion program: {0}.
        /// </summary>
        public static string UserAlreasdyEnrolled {
            get {
                return ResourceManager.GetString("UserAlreasdyEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your domain doesn&apos;t match this promotion program domains.
        /// </summary>
        public static string UserDomianDosntExistInProgramDomains {
            get {
                return ResourceManager.GetString("UserDomianDosntExistInProgramDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle type is not valid.
        /// </summary>
        public static string VehicleTypeIdInvalid {
            get {
                return ResourceManager.GetString("VehicleTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email was sent to this email: {0} .Please see your inbox..
        /// </summary>
        public static string VerificationMailAlreadySent {
            get {
                return ResourceManager.GetString("VerificationMailAlreadySent", resourceCulture);
            }
        }
    }
}
