//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Integration.Providers.ArabianShield.ArabianShieldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArabianShieldService.IBcareTameenk")]
    public interface IBcareTameenk {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcareTameenk/Quotation", ReplyAction="http://tempuri.org/IBcareTameenk/QuotationResponse")]
        string Quotation(string Quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcareTameenk/Quotation", ReplyAction="http://tempuri.org/IBcareTameenk/QuotationResponse")]
        System.Threading.Tasks.Task<string> QuotationAsync(string Quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcareTameenk/Policy", ReplyAction="http://tempuri.org/IBcareTameenk/PolicyResponse")]
        string Policy([System.ServiceModel.MessageParameterAttribute(Name="Policy")] string Policy1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcareTameenk/Policy", ReplyAction="http://tempuri.org/IBcareTameenk/PolicyResponse")]
        System.Threading.Tasks.Task<string> PolicyAsync(string Policy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBcareTameenkChannel : Tameenk.Integration.Providers.ArabianShield.ArabianShieldService.IBcareTameenk, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BcareTameenkClient : System.ServiceModel.ClientBase<Tameenk.Integration.Providers.ArabianShield.ArabianShieldService.IBcareTameenk>, Tameenk.Integration.Providers.ArabianShield.ArabianShieldService.IBcareTameenk {
        
        public BcareTameenkClient() {
        }
        
        public BcareTameenkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BcareTameenkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcareTameenkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcareTameenkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Quotation(string Quote) {
            return base.Channel.Quotation(Quote);
        }
        
        public System.Threading.Tasks.Task<string> QuotationAsync(string Quote) {
            return base.Channel.QuotationAsync(Quote);
        }
        
        public string Policy(string Policy1) {
            return base.Channel.Policy(Policy1);
        }
        
        public System.Threading.Tasks.Task<string> PolicyAsync(string Policy) {
            return base.Channel.PolicyAsync(Policy);
        }
    }
}
