DROP TABLE [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetClinetClaims]
DROP TABLE [dbo].[AspNetAdmins]