//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.Resources.Checkout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckoutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.Resources.Checkout.CheckoutResources", typeof(CheckoutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account is Locked, Please Contact Customer Service 8001180044 (NA-99).
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Activation.
        /// </summary>
        public static string ActivateEmailToReceivePolicySubject {
            get {
                return ResourceManager.GetString("ActivateEmailToReceivePolicySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already paied before.
        /// </summary>
        public static string AlreadyPaidBefore {
            get {
                return ResourceManager.GetString("AlreadyPaidBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By approving to this declaration, you acknowledge and undertake that all the data and information about you in the quotation submitted to Buruj are correct and under your full responsibility, and you also acknowledge that your national address registered in Saudi Post, which appears in the quotation is your actual and correct address, and in the event of a difference address. You should review the Saudi Post for modification before completing the issuance of the policy, as this data may affect the company’s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BurujTermsAndConditions {
            get {
                return ResourceManager.GetString("BurujTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No is different than registered in database , sms will be send to you for verification.
        /// </summary>
        public static string Checkout_AnotherCheckoutMobileNumberUserd {
            get {
                return ResourceManager.GetString("Checkout_AnotherCheckoutMobileNumberUserd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail.
        /// </summary>
        public static string checkout_error_email {
            get {
                return ResourceManager.GetString("checkout_error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile number.
        /// </summary>
        public static string checkout_error_phone {
            get {
                return ResourceManager.GetString("checkout_error_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue has been happened during Esal payment. please try again later.
        /// </summary>
        public static string Checkout_Esalpayment_instruction_error {
            get {
                return ResourceManager.GetString("Checkout_Esalpayment_instruction_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance company contact is invalid.
        /// </summary>
        public static string Checkout_InsuranceCompanyContactInvalid {
            get {
                return ResourceManager.GetString("Checkout_InsuranceCompanyContactInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN accept numbers with only one char.
        /// </summary>
        public static string Checkout_InvalidIBAN {
            get {
                return ResourceManager.GetString("Checkout_InvalidIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input parameter.
        /// </summary>
        public static string Checkout_InvalidInputParameter {
            get {
                return ResourceManager.GetString("Checkout_InvalidInputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payfort parameters are invalid.
        /// </summary>
        public static string Checkout_PayfortParameters_invalid {
            get {
                return ResourceManager.GetString("Checkout_PayfortParameters_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payfort checkout is invalid.
        /// </summary>
        public static string Checkout_PayfortPaymentIsInvalid {
            get {
                return ResourceManager.GetString("Checkout_PayfortPaymentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payfort requestId is null.
        /// </summary>
        public static string Checkout_PayfortRequestIdIsNull {
            get {
                return ResourceManager.GetString("Checkout_PayfortRequestIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QtsRqsExtrnlIds is null.
        /// </summary>
        public static string Checkout_QtRqstExtrnlIdIsNull {
            get {
                return ResourceManager.GetString("Checkout_QtRqstExtrnlIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request policy effective date is less than 16hr..
        /// </summary>
        public static string Checkout_QuotationRequest_RequestPolicyEffectiveDateIsNotValid {
            get {
                return ResourceManager.GetString("Checkout_QuotationRequest_RequestPolicyEffectiveDateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceId is null.
        /// </summary>
        public static string Checkout_ReferenceIdIsNull {
            get {
                return ResourceManager.GetString("Checkout_ReferenceIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue has been happened during Sadad payment. please try again later.
        /// </summary>
        public static string Checkout_Sadadpayment_instruction_error {
            get {
                return ResourceManager.GetString("Checkout_Sadadpayment_instruction_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart quotation response is not within 16hr..
        /// </summary>
        public static string Checkout_ShoppingCartItemIsNotValid {
            get {
                return ResourceManager.GetString("Checkout_ShoppingCartItemIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart Item is null.
        /// </summary>
        public static string Checkout_ShoppingCartItemIsNull {
            get {
                return ResourceManager.GetString("Checkout_ShoppingCartItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a payment error using Tabby. Please try again later or use other payment methods..
        /// </summary>
        public static string Checkout_Tabbbypayment_instruction_error1 {
            get {
                return ResourceManager.GetString("Checkout_Tabbbypayment_instruction_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data for this request.
        /// </summary>
        public static string CheckoutIsNull {
            get {
                return ResourceManager.GetString("CheckoutIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout model is null.
        /// </summary>
        public static string CheckoutModelIsNullException {
            get {
                return ResourceManager.GetString("CheckoutModelIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This discount code already consumed before.
        /// </summary>
        public static string CodeConsumedBefore {
            get {
                return ResourceManager.GetString("CodeConsumedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Vehicle Insurance.
        /// </summary>
        public static string COMP {
            get {
                return ResourceManager.GetString("COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACIG Plus Insurance.
        /// </summary>
        public static string COMP_ACIG {
            get {
                return ResourceManager.GetString("COMP_ACIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Motor Insurance.
        /// </summary>
        public static string COMP_Rajhi {
            get {
                return ResourceManager.GetString("COMP_Rajhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive.
        /// </summary>
        public static string COMP_SMS {
            get {
                return ResourceManager.GetString("COMP_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aman ALETIHAD.
        /// </summary>
        public static string COMP_TUIC {
            get {
                return ResourceManager.GetString("COMP_TUIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPL&amp;OD.
        /// </summary>
        public static string COMP_UCA {
            get {
                return ResourceManager.GetString("COMP_UCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount code is Expired.
        /// </summary>
        public static string DiscountCodeExpired {
            get {
                return ResourceManager.GetString("DiscountCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount code not exit.
        /// </summary>
        public static string DiscountCodeNotExist {
            get {
                return ResourceManager.GetString("DiscountCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Driver Nin: {0}, Vehicle: {1} , has an active policy.
        /// </summary>
        public static string DriverNinWithVehicleIdHasActivePolicies {
            get {
                return ResourceManager.GetString("DriverNinWithVehicleIdHasActivePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded Sadad maximum limit for today, please try again after {0}.
        /// </summary>
        public static string EdaatNumberReachedToMaximum {
            get {
                return ResourceManager.GetString("EdaatNumberReachedToMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is activated.
        /// </summary>
        public static string EmailActivated {
            get {
                return ResourceManager.GetString("EmailActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;m_bg_white&quot; width=&quot;50%&quot; align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;background-color: #F5F9FD;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;850&quot; align=&quot;center&quot; &gt;
        ///                &lt;table width=&quot;100%&quot;  border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;
        ///                    style=&quot;border-collapse:collapse&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td class=&quot;m_overflow135 m_fs16&quot; align=&quot;center&quot;
        ///                            style=&quot;font-family:helvetica neue,helvetica,arial,sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailActivationBodyToReceivePolicy {
            get {
                return ResourceManager.GetString("EmailActivationBodyToReceivePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email assigned to another driver so please enter the insured email.
        /// </summary>
        public static string EmailUsedWithAnotherDriver {
            get {
                return ResourceManager.GetString("EmailUsedWithAnotherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (NA-99).
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login to complete the action.
        /// </summary>
        public static string ErrorAnonymous {
            get {
                return ResourceManager.GetString("ErrorAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (G-01).
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured, Please contact Customer Service 8001180044 (G-01).
        /// </summary>
        public static string ErrorGenericApplePay {
            get {
                return ResourceManager.GetString("ErrorGenericApplePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (E-01).
        /// </summary>
        public static string ErrorGenericException {
            get {
                return ResourceManager.GetString("ErrorGenericException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (H-01).
        /// </summary>
        public static string ErrorHashing {
            get {
                return ResourceManager.GetString("ErrorHashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (R-01).
        /// </summary>
        public static string ErrorNoRecordFound {
            get {
                return ResourceManager.GetString("ErrorNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please contact Customer Service 8001180044 (S-01).
        /// </summary>
        public static string ErrorSecurity {
            get {
                return ResourceManager.GetString("ErrorSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error occurred while cancelling previous sadad invoice at sadad, Please try again.
        /// </summary>
        public static string FailedToCancelInvoiceAtSadad {
            get {
                return ResourceManager.GetString("FailedToCancelInvoiceAtSadad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error occurred while cancelling the previous invoice, Please try again.
        /// </summary>
        public static string FailedToDeleteOldInvoice {
            get {
                return ResourceManager.GetString("FailedToDeleteOldInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN accept numbers only.
        /// </summary>
        public static string IBAN_Validation {
            get {
                return ResourceManager.GetString("IBAN_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN already used before for another driver.
        /// </summary>
        public static string IBANUsedForOtherDriver {
            get {
                return ResourceManager.GetString("IBANUsedForOtherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The international bank account number is invalid please make sure from the number.
        /// </summary>
        public static string IBANValidationError {
            get {
                return ResourceManager.GetString("IBANValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The national address city does not match the driving city..
        /// </summary>
        public static string InsuredCityDoesNotMatchAddressCity {
            get {
                return ResourceManager.GetString("InsuredCityDoesNotMatchAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild request.
        /// </summary>
        public static string InvaildRequest {
            get {
                return ResourceManager.GetString("InvaildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riyad bank response is invalid.
        /// </summary>
        public static string Invalid_RiyadBankResponse {
            get {
                return ResourceManager.GetString("Invalid_RiyadBankResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Verify Code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN accept numbers with only one char with maximum length 22 number.
        /// </summary>
        public static string InvalidIBANlength {
            get {
                return ResourceManager.GetString("InvalidIBANlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment process failed..
        /// </summary>
        public static string InvalidPayment {
            get {
                return ResourceManager.GetString("InvalidPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Method.
        /// </summary>
        public static string InvalidPaymentMethod {
            get {
                return ResourceManager.GetString("InvalidPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method is under maintenance, please choose another payment method.
        /// </summary>
        public static string InvalidPaymentMethods {
            get {
                return ResourceManager.GetString("InvalidPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is cancelled before.
        /// </summary>
        public static string IsCancelled {
            get {
                return ResourceManager.GetString("IsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not renewal.
        /// </summary>
        public static string IsRenewalError {
            get {
                return ResourceManager.GetString("IsRenewalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;processNo2Div&quot; class=&quot;row content-process process-number-2&quot;&gt;
        ///    &lt;div style=&quot;text-align:center;font-size:20px;&quot;&gt;
        ///        &lt;h4 style=&quot;color: red;&quot;&gt;Alert your data is incomplete &lt;/h4&gt;
        ///        
        ///        &lt;p style=text-align:center!important;&quot;&gt;As per SAMA regulations, National Address is mandatory when issuing the policy and for any types of insurance, Register now by clicking 
        ///        &quot;&lt;a style=&quot;float:none!important;&quot; target=&quot;_blank&quot; href=&quot;https://register.address.gov.sa/ar/default.aspx&quot;&gt;here&lt;/a&gt;&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MissingAddress {
            get {
                return ResourceManager.GetString("MissingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert all vehicle images..
        /// </summary>
        public static string MissingCarImages {
            get {
                return ResourceManager.GetString("MissingCarImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Plus.
        /// </summary>
        public static string MotorPlus {
            get {
                return ResourceManager.GetString("MotorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing national address validation. Please try again later.
        /// </summary>
        public static string NationalAddressVlidationError {
            get {
                return ResourceManager.GetString("NationalAddressVlidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing number of accident validation. Please try again later.
        /// </summary>
        public static string NumberOfAccidentVlidationError {
            get {
                return ResourceManager.GetString("NumberOfAccidentVlidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Succeeded.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone  number assigned to another driver so please enter the insured mobile number.
        /// </summary>
        public static string PhoneNoWithAnotherDriver {
            get {
                return ResourceManager.GetString("PhoneNoWithAnotherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy already avaiable .
        /// </summary>
        public static string PolicyAlreadyAvaiable {
            get {
                return ResourceManager.GetString("PolicyAlreadyAvaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Price.
        /// </summary>
        public static string PolicyPrice {
            get {
                return ResourceManager.GetString("PolicyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation expired, please get another quotation..
        /// </summary>
        public static string QuotationExpired {
            get {
                return ResourceManager.GetString("QuotationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download Quotation Form Frist.
        /// </summary>
        public static string QuotationFormNotFound {
            get {
                return ResourceManager.GetString("QuotationFormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh quotations prices .
        /// </summary>
        public static string RefreshQuotation {
            get {
                return ResourceManager.GetString("RefreshQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation is Expired.
        /// </summary>
        public static string RequestPolicyEffectiveDateIsNotValidForSAICO {
            get {
                return ResourceManager.GetString("RequestPolicyEffectiveDateIsNotValidForSAICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information will be sent via sms and email.
        /// </summary>
        public static string SadadMessage {
            get {
                return ResourceManager.GetString("SadadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanad plus.
        /// </summary>
        public static string SANADPLUS {
            get {
                return ResourceManager.GetString("SANADPLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qutotation request with external identifier {0} not found.
        /// </summary>
        public static string Tameenk_ArgumentNullException_Quotation {
            get {
                return ResourceManager.GetString("Tameenk_ArgumentNullException_Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you exceeded purchase amount with this email..
        /// </summary>
        public static string Tameenk_MaxCheckoutEmail_Error {
            get {
                return ResourceManager.GetString("Tameenk_MaxCheckoutEmail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough balance.
        /// </summary>
        public static string ThereIsNotEnoughBalance {
            get {
                return ResourceManager.GetString("ThereIsNotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Vehicle Insurance.
        /// </summary>
        public static string TPL {
            get {
                return ResourceManager.GetString("TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPL.
        /// </summary>
        public static string TPL_SMS {
            get {
                return ResourceManager.GetString("TPL_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to contact with the insurance company directly, as you have more than 5 insured vehicles for the same insured person..
        /// </summary>
        public static string UserExceedsInsuranceNumberLimitCheckoutPopup {
            get {
                return ResourceManager.GetString("UserExceedsInsuranceNumberLimitCheckoutPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Exceeded the maximum allowed limit for requesting sadad bill id, You can pay by other payment options.
        /// </summary>
        public static string VehicleExceededSadadLimit {
            get {
                return ResourceManager.GetString("VehicleExceededSadadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code for phone no is {0}.
        /// </summary>
        public static string VerificationCodeMessage {
            get {
                return ResourceManager.GetString("VerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafi Smart.
        /// </summary>
        public static string WAFISMART {
            get {
                return ResourceManager.GetString("WAFISMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend while checking Draft policy, please try again later.
        /// </summary>
        public static string WataniyaDraftPolicyError {
            get {
                return ResourceManager.GetString("WataniyaDraftPolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not deserve the discount.
        /// </summary>
        public static string YouDoNotDeserveTheDiscount {
            get {
                return ResourceManager.GetString("YouDoNotDeserveTheDiscount", resourceCulture);
            }
        }
    }
}
